name: Download Videos ytdlp

on:
  workflow_dispatch:

jobs:
  download-videos:
    runs-on: windows-2025  # Use latest available Windows runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install ffmpeg
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri https://www.gyan.dev/ffmpeg/builds/ffmpeg-release-essentials.zip -OutFile ffmpeg.zip
          Expand-Archive ffmpeg.zip -DestinationPath $Env:USERPROFILE\ffmpeg
          $Env:PATH += ";$Env:USERPROFILE\ffmpeg\ffmpeg-release-essentials\bin"
          echo "FFMPEG_PATH=$Env:USERPROFILE\ffmpeg\ffmpeg-release-essentials\bin" >> $Env:GITHUB_ENV
          # Verify installation
          & $Env:USERPROFILE\ffmpeg\ffmpeg-release-essentials\bin\ffmpeg.exe -version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Reel Downloader script
        run: |
          python reeldownloader_ytdlp.py

      - name: Commit counter.txt if changed
        run: |
          if ((git diff --quiet counter.txt)) {
            Write-Host "No changes to counter.txt"
          } else {
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add counter.txt
            git commit -m "Update counter.txt"
            git pull --rebase origin main || Write-Host "No changes to pull"
            git push origin main
            Write-Host "Committed and pushed counter.txt"
          }

      - name: Commit links.txt if changed
        run: |
          if ((git diff --quiet links.txt)) {
            Write-Host "No changes to links.txt"
          } else {
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add links.txt
            git commit -m "Update links.txt"
            git pull --rebase origin main || Write-Host "No changes to pull"
            git push origin main
            Write-Host "Committed and pushed links.txt"
          }

      - name: Commit videos in batches of 50
        shell: bash
        run: |
          # Get list of untracked files in VIDEOS/
          mapfile -t files < <(git ls-files --others --exclude-standard VIDEOS/)

          # Filter out VIDEOS/Video_0.mp4
          filtered_files=()
          for file in "${files[@]}"; do
            if [[ "$file" != "VIDEOS/Video_0.mp4" ]]; then
              filtered_files+=("$file")
            fi
          done

          total=${#filtered_files[@]}
          batch_size=50

          echo "Total files to commit: $total"
          echo "Batch size: $batch_size"

          for ((i=0; i<$total; i+=$batch_size)); do
            batch=("${filtered_files[@]:i:batch_size}")
            echo "Processing batch: $((i+1)) to $((i + ${#batch[@]}))"
            echo "Files added to staging: ${batch[@]}"

            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"

            git add "${batch[@]}"
            git commit -m "Batch commit: files $((i+1)) to $((i + ${#batch[@]}))"
            echo "Committed batch: $((i+1)) to $((i + ${#batch[@]}))"

            git pull --rebase origin main || echo "No changes to pull"
            git push origin main
            echo "Pushed batch: $((i+1)) to $((i + ${#batch[@]}))"
          done

