name: Download Videos

on:
  workflow_dispatch:

jobs:
  download-videos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Selenium script
        run: |
          python ReelDownloader.py

      - name: Commit in batches of 5
        run: |
          cd VIDEOS
          files=(*)
          total=${#files[@]}
          batch_size=5

          echo "Total files to commit: $total"
          echo "Batch size: $batch_size"

          cd ..
          for ((i=0; i<$total; i+=$batch_size)); do
            batch=("${files[@]:i:batch_size}")
            echo "Processing batch: $((i+1)) to $((i + ${#batch[@]}))"
            echo "Files added to staging: ${batch[@]}"

            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"

            git add "${batch[@]/#/VIDEOS/}"  # Prepend path since we're back in repo root
            git commit -m "Batch commit: files $((i+1)) to $((i + ${#batch[@]}))"
            echo "Committed batch: $((i+1)) to $((i + ${#batch[@]}))"

            git push origin main
            echo "Pushed batch: $((i+1)) to $((i + ${#batch[@]}))"
          done

      - name: Commit counter.txt if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add counter.txt
          git commit -m "Update counter.txt"
          git push origin main
          echo "Committed and pushed counter.txt"
          